# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
target ‘d07’ do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for d07
  pod 'JSONJoy-Swift', '~> 1.0.1'
  pod 'Alamofire', '~> 3.5.0'
  pod 'RecastAI'
  pod 'ForecastIO', :git => 'https://github.com/sxg/ForecastIO.git', :branch => 'swift2.3'
  pod 'JSQMessagesViewController'
end